# 教學目標:
了解 Convolution 卷積的組成 <br />

# 範例內容:
定義單步的卷積 <br />
<br />
輸出卷積的計算值<br />

In [0]:
import numpy as np

In [0]:
#graded function : conv_single_step

def conv_single_step(a_slice_prev, w, b):
    """
    a_slice_prev : input data dimension
    w : weights 
    b : bias
    
    return z : the convolution result of sliding window (w,b) on prev feature map
    """
    
    s = a_slice_prev * w
    z = np.sum(s)
    z = float(z + b)
    
    return z

In [5]:
'''
seed( ) 用於指定隨機數生成時所用算法開始的整數值，
如果使用相同的seed( )值，則每次生成的隨即數都相同，
如果不設置這個值，則係統根據時間來自己選擇這個值，
此時每次生成的隨機數因時間差異而不同。
'''

np.random.seed(1)
#define a 4x4x3 feature map
a_slice_prev = np.random.randn(4,4,3)
w = np.random.randn(4,4,3)
b = np.random.randn(1,1,1)


z = conv_single_step(a_slice_prev, w, b)
print(f' z = {z}')

 z = -6.999089450680221


# 作業目標:
了解 Convolution 卷積的組成 <br />
# 作業重點:
修改 a_slice_prev, 檢查 Z 的輸出<br />

In [0]:
#Assume the image is square
def conv_single_filter(a_slice_prev, kernel, b):
  
    feature_map_size = a_slice_prev.shape[0] - kernel.shape[0] + 1
    feature_map = np.zeros(feature_map_size ** 2)
    
    kernel_size = kernel.shape[0]
    image_size = a_slice_prev.shape[0]
    feature_idx = 0
    for i in range(image_size - kernel_size + 1):
      for j in range(image_size- kernel_size + 1):
        part_img = a_slice_prev[i:kernel_size+i, j:kernel_size+j]
        s = part_img * kernel
        feature_map[feature_idx] = np.sum(s)
        feature_map[feature_idx] = float(feature_map[feature_idx] + b)
        feature_idx += 1

    return feature_map.reshape(feature_map_size, feature_map_size)
  
  
  
  
  
  
  

In [36]:
np.random.seed(1)
a_slice_prev = np.random.randn(6,6,1)
kernel = np.ones((3,3,1), dtype = int)
b = np.random.randn(1,1,1)

feature_map = conv_single_filter(a_slice_prev, kernel, b)

print("Image:")
print(a_slice_prev.reshape(6,6))
print("-"*10)
print("kernel:")
print(kernel.reshape(3,3))
print("-"*10)
print("Convolution result:")
print(feature_map)

Image:
[[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391  -0.24937038  1.46210794 -2.06014071]
 [-0.3224172  -0.38405435  1.13376944 -1.09989127 -0.17242821 -0.87785842]
 [ 0.04221375  0.58281521 -1.10061918  1.14472371  0.90159072  0.50249434]
 [ 0.90085595 -0.68372786 -0.12289023 -0.93576943 -0.26788808  0.53035547]
 [-0.69166075 -0.39675353 -0.6871727  -0.84520564 -0.67124613 -0.0126646 ]]
----------
kernel:
[[1 1 1]
 [1 1 1]
 [1 1 1]]
----------
Convolution result:
[[ 1.09704869 -4.3719215  -0.45981647 -6.62399108]
 [ 0.13704128 -1.53210496  1.22161153 -1.56608262]
 [-1.07136482 -2.5829543  -1.63671287 -1.39198152]
 [-3.27424968 -4.16190999 -3.70178731 -0.77092   ]]
